config/routes.rb
Rails.application.routes.draw do
  resources :vendas_produtos
  resources :vendas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/venda.rb
class Venda < ApplicationRecord
  has_many :vendas_produtos, dependent: :destroy
  accepts_nested_attributes_for :vendas_produtos, allow_destroy: true
end

app/models/vendas_produto.rb
class VendasProduto < ApplicationRecord
  belongs_to :venda
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: %i[ show edit update destroy ]

  # GET /vendas or /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1 or /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = Venda.new
    @venda.vendas_produtos.build   # ← ESSA LINHA É FUNDAMENTAL
  end


  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas or /vendas.json
  def create
    @venda = Venda.new(venda_params)

    respond_to do |format|
      if @venda.save
        format.html { redirect_to @venda, notice: "Venda was successfully created." }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1 or /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to @venda, notice: "Venda was successfully updated." }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1 or /vendas/1.json
  def destroy
    @venda.destroy!

    respond_to do |format|
      format.html { redirect_to vendas_path, status: :see_other, notice: "Venda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params.expect(:id))
    end

  def venda_params
    params.require(:venda).permit(:cliente, vendas_produtos_attributes: [:id, :produto, :quantidade, :valor, :_destroy])
  end
end

app/controllers/vendas_produtos_controller.rb
class VendasProdutosController < ApplicationController
  before_action :set_vendas_produto, only: %i[ show edit update destroy ]

  # GET /vendas_produtos or /vendas_produtos.json
  def index
    @vendas_produtos = VendasProduto.all
  end

  # GET /vendas_produtos/1 or /vendas_produtos/1.json
  def show
  end

  # GET /vendas_produtos/new
  def new
    @vendas_produto = VendasProduto.new
  end

  # GET /vendas_produtos/1/edit
  def edit
  end

  # POST /vendas_produtos or /vendas_produtos.json
  def create
    @vendas_produto = VendasProduto.new(vendas_produto_params)

    respond_to do |format|
      if @vendas_produto.save
        format.html { redirect_to @vendas_produto, notice: "Vendas produto was successfully created." }
        format.json { render :show, status: :created, location: @vendas_produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendas_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas_produtos/1 or /vendas_produtos/1.json
  def update
    respond_to do |format|
      if @vendas_produto.update(vendas_produto_params)
        format.html { redirect_to @vendas_produto, notice: "Vendas produto was successfully updated." }
        format.json { render :show, status: :ok, location: @vendas_produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendas_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas_produtos/1 or /vendas_produtos/1.json
  def destroy
    @vendas_produto.destroy!

    respond_to do |format|
      format.html { redirect_to vendas_produtos_path, status: :see_other, notice: "Vendas produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendas_produto
      @vendas_produto = VendasProduto.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def vendas_produto_params
      params.expect(vendas_produto: [ :venda_id, :produto, :quantidade, :valor ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/helpers/vendas_produtos_helper.rb
module VendasProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crud Vendas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vendas/_form.html.erb
<%= form_with(model: venda) do |form| %>
  <%= form.label :cliente %>
  <%= form.text_field :cliente %>

  <h3>Produtos</h3>
  <%= form.fields_for :vendas_produtos do |produto_form| %>
    <div>
      <%= produto_form.label :produto %>
      <%= produto_form.text_field :produto %>

      <%= produto_form.label :quantidade %>
      <%= produto_form.number_field :quantidade %>

      <%= produto_form.label :valor %>
      <%= produto_form.number_field :valor, step: 0.01 %>

      <%= produto_form.check_box :_destroy %>
      <%= produto_form.label :_destroy, "Remover" %>
    </div>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/vendas/_venda.html.erb
<div id="<%= dom_id venda %>">
  <p>
    <strong>Cliente:</strong>
    <%= venda.cliente %>
  </p>

</div>

app/views/vendas/edit.html.erb
<% content_for :title, "Editing venda" %>

<h1>Editing venda</h1>

<%= render "form", venda: @venda %>

<br>

<div>
  <%= link_to "Show this venda", @venda %> |
  <%= link_to "Back to vendas", vendas_path %>
</div>

app/views/vendas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Vendas" %>

<h1>Vendas</h1>

<div id="vendas">
  <% @vendas.each do |venda| %>
    <%= render venda %>
    <p>
      <%= link_to "Show this venda", venda %>
    </p>
  <% end %>
</div>

<%= link_to "New venda", new_venda_path %>

app/views/vendas/new.html.erb
<% content_for :title, "New venda" %>

<h1>New venda</h1>

<%= render "form", venda: @venda %>

<br>

<div>
  <%= link_to "Back to vendas", vendas_path %>
</div>

app/views/vendas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @venda %>

<div>
  <%= link_to "Edit this venda", edit_venda_path(@venda) %> |
  <%= link_to "Back to vendas", vendas_path %>

  <%= button_to "Destroy this venda", @venda, method: :delete %>
</div>

app/views/vendas_produtos/_form.html.erb
<%= form_with(model: vendas_produto) do |form| %>
  <% if vendas_produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vendas_produto.errors.count, "error") %> prohibited this vendas_produto from being saved:</h2>

      <ul>
        <% vendas_produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :venda_id, style: "display: block" %>
    <%= form.text_field :venda_id %>
  </div>

  <div>
    <%= form.label :produto, style: "display: block" %>
    <%= form.text_field :produto %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vendas_produtos/_vendas_produto.html.erb
<div id="<%= dom_id vendas_produto %>">
  <p>
    <strong>Venda:</strong>
    <%= vendas_produto.venda_id %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= vendas_produto.produto %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= vendas_produto.quantidade %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= vendas_produto.valor %>
  </p>

</div>

app/views/vendas_produtos/edit.html.erb
<% content_for :title, "Editing vendas produto" %>

<h1>Editing vendas produto</h1>

<%= render "form", vendas_produto: @vendas_produto %>

<br>

<div>
  <%= link_to "Show this vendas produto", @vendas_produto %> |
  <%= link_to "Back to vendas produtos", vendas_produtos_path %>
</div>

app/views/vendas_produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Vendas produtos" %>

<h1>Vendas produtos</h1>

<div id="vendas_produtos">
  <% @vendas_produtos.each do |vendas_produto| %>
    <%= render vendas_produto %>
    <p>
      <%= link_to "Show this vendas produto", vendas_produto %>
    </p>
  <% end %>
</div>

<%= link_to "New vendas produto", new_vendas_produto_path %>

app/views/vendas_produtos/new.html.erb
<% content_for :title, "New vendas produto" %>

<h1>New vendas produto</h1>

<%= render "form", vendas_produto: @vendas_produto %>

<br>

<div>
  <%= link_to "Back to vendas produtos", vendas_produtos_path %>
</div>

app/views/vendas_produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vendas_produto %>

<div>
  <%= link_to "Edit this vendas produto", edit_vendas_produto_path(@vendas_produto) %> |
  <%= link_to "Back to vendas produtos", vendas_produtos_path %>

  <%= button_to "Destroy this vendas produto", @vendas_produto, method: :delete %>
</div>